//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JinderWebApp.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JinderDBConnection : DbContext
    {
        public JinderDBConnection()
            : base("name=JinderDBConnection")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChatMessage> ChatMessages { get; set; }
        public virtual DbSet<JinderUser> JinderUsers { get; set; }
        public virtual DbSet<JobPost> JobPosts { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<PosterExpressionLog> PosterExpressionLogs { get; set; }
        public virtual DbSet<SeekerExpressionLog> SeekerExpressionLogs { get; set; }
        public virtual DbSet<SeekerProfile> SeekerProfiles { get; set; }
    }
}
