//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JinderWebApp.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeekerExpressionLog
    {
        public int SeekerExpressionLogId { get; set; }
        public int SeekerId { get; set; }
        public int JobPostId { get; set; }
        public bool isInterested { get; set; }
        public System.DateTime ExpressionDate { get; set; }
    
        public virtual JinderUser JinderUser { get; set; }
        public virtual JobPost JobPost { get; set; }
    }
}
